#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Aug 03 18:21:13 COT 2026
allowUnknownShaders=false
colorSpace=REC2020
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=iterationT 3.2.0.zip
