#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 09 14:11:28 COT 2026
allowUnknownShaders=false
colorSpace=REC2020
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Derivative Main d24.4.4.zip
